picoos-oo: nos::Timer Class Reference
nos::Timer Class Reference
#include <picoos-timer.hxx>
Public Member Functions
VAR_t create (const char *name)
void destroy ()
Public Member Functions inherited from pos::Timer
VAR_t create ()
VAR_t set (const Sema &sema, UINT_t waitticks, UINT_t periodticks)
VAR_t start ()
VAR_t stop ()
void destroy ()
VAR_t fired ()
Detailed Description
Timer functions.
Member Function Documentation
create()
VAR_t nos::Timer::create (const char * name) inline
Allocates a timer object. After a timer is allocated with this function, it must be set up with nosTimerSet and than started with nosTimerStart.
Returns
semaphore creation status. -1 is returned when the semaphore could not be created.
Parameters
name Name of the new timer object to create. If the last character in the name is an asteriks (*), the operating system automatically assigns the timer an unique name (the registry feature must be enabled for this automatism). This parameter can be NULL if the nano layer registry feature is not used and will not be used in future.
Note
NOSCFG_FEATURE_TIMER must be defined to 1 to have timer support compiled in.
You must use nosTimerDestroy to destroy the flag object again.
Even if the function posTimerDestroy would work also, it is required to call nosTimerDestroy. Only this function removes the flag object from the registry.
Dependent of your configuration, this function can be defined as macro to decrease code size.
See also
nosTimerSet, nosTimerStart, nosTimerDestroy
References pos::Timer::create(), and nosTimerCreate().
destroy()
void nos::Timer::destroy () inline
Deletes a timer object and free its resources.
Note
NOSCFG_FEATURE_TIMER must be defined to 1 to have timer support compiled in.
POSCFG_FEATURE_TIMERDESTROY must be defined to 1 to have this function compiled in.
Dependent of your configuration, this function can be defined as macro to decrease code size.
See also
nosTimerCreate
References nosTimerDestroy().