picoos-oo: pos::Task Class Reference
pos::Task Class Reference
#include <picoos-task.hxx>
Public Member Functions
VAR_t create (POSTASKFUNC_t funcptr, void *funcarg, VAR_t priority, void *stackstart)
VAR_t create (POSTASKFUNC_t funcptr, void *funcarg, VAR_t priority, UINT_t stacksize)
VAR_t create (POSTASKFUNC_t funcptr, void *funcarg, VAR_t priority)
VAR_t unused ()
VAR_t setPriority (VAR_t priority)
VAR_t getPriority ()
void setName (const char *name)
Static Public Member Functions
static void yield (void)
static void sleep (UINT_t ticks)
static void init (POSTASKFUNC_t firstfunc, void *funcarg, VAR_t priority, void *stackFirstTask, void *stackIdleTask)
static void init (POSTASKFUNC_t firstfunc, void *funcarg, VAR_t priority, UINT_t taskStackSize, UINT_t idleStackSize)
static void init (POSTASKFUNC_t firstfunc, void *funcarg, VAR_t priority)
static void exit (void)
static Task getCurrent (void)
static void schedLock (void)
static void schedUnlock (void)
static void * getUserspace (void)
static POSIDLEFUNC_t installIdleTaskHook (POSIDLEFUNC_t idlefunc)
Detailed Description
Task Control
Member Function Documentation
static void pos::Task::yield (void) inline static
This function can be called to give off processing time so other tasks ready to run will be scheduled (= cooparative multitasking).
Note
POSCFG_FEATURE_YIELD must be defined to 1 to have this function compiled in.
See also
posTaskYield, sleep
References posTaskYield().
static void pos::Task::sleep (UINT_t ticks) inline static
Delay task execution for a couple of timer ticks.
Parameters
ticks delay time in timer ticks (see HZ define and MS macro)
Note
POSCFG_FEATURE_SLEEP must be defined to 1 to have this function compiled in.
It is not guaranteed that the task will proceed execution exactly when the time has elapsed. A higher priorized task or a task having the same priority may steal the processing time. Sleeping a very short time is inaccurate.
See also
posTaskSleep, yield, HZ, MS
References posTaskSleep().
VAR_t pos::Task::create (POSTASKFUNC_t funcptr, void * funcarg, VAR_t priority, void * stackstart) inline
Creates a new task. The stack memory is managed by the user.
Parameters
funcptr pointer to the function that shall be executed by the new task.
funcarg optional argument passed to function.
priority task priority. Must be in the range 0 .. POSCFG_MAX_PRIO_LEVEL - 1. The higher the number, the higher the priority.
stackstart pointer to the stack memory for the new task. task could not be created.
Returns
task creation status. -1 is returned when the task could not be created.
Note
POSCFG_TASKSTACKTYPE must be defined to 0 to have this format of the function compiled in.
See also
posTaskCreate, exit
References posTaskCreate().
static void pos::Task::init (POSTASKFUNC_t firstfunc, void * funcarg, VAR_t priority, void * stackFirstTask, void * stackIdleTask) inline static
Operating System Initialization. This function initializes the operating system and starts the first tasks: The idle task and the first user task.
Parameters
firstfunc pointer to the first task function that will run in the multitasking environment.
funcarg optional argument passed to the first task.
priority task priority. Must be in the range 0 .. POSCFG_MAX_PRIO_LEVEL - 1. The higher the number, the higher the priority.
stackFirstTask pointer to the stack memory for the first task.
stackIdleTask pointer to the stack memory for the idle task.
Note
POSCFG_TASKSTACKTYPE must be defined to 0 to have this format of the function compiled in.
See also
posInit
References posInit().
VAR_t pos::Task::create (POSTASKFUNC_t funcptr, void * funcarg, VAR_t priority, UINT_t stacksize) inline
Creates a new task. The stack memory is managed by the achitecture specific portion of the operating system, the size can be set by the user.
Parameters
funcptr pointer to the function that shall be executed by the new task.
funcarg optional argument passed to function.
priority task priority. Must be in the range 0 .. POSCFG_MAX_PRIO_LEVEL - 1. The higher the number, the higher the priority.
stacksize size of the stack memory. This parameter is passed to the architecture specific portion of the operating system.
Returns
task creation status. -1 is returned when the task could not be created.
Note
POSCFG_TASKSTACKTYPE must be defined to 1 to have this format of the function compiled in.
See also
posTaskCreate, exit
References posTaskCreate().
static void pos::Task::init (POSTASKFUNC_t firstfunc, void * funcarg, VAR_t priority, UINT_t taskStackSize, UINT_t idleStackSize) inline static
Operating System Initialization. This function initializes the operating system and starts the first tasks: The idle task and the first user task.
Parameters
firstfunc pointer to the first task function that will run in the multitasking environment.
funcarg optional argument passed to the first task.
priority task priority. Must be in the range 0 .. POSCFG_MAX_PRIO_LEVEL - 1. The higher the number, the higher the priority.
taskStackSize size of the stack memory for the first task.
idleStackSize size of the stack memory for the idle task.
Note
POSCFG_TASKSTACKTYPE must be defined to 1 to have this format of the function compiled in.
See also
posInit
References posInit().
VAR_t pos::Task::create (POSTASKFUNC_t funcptr, void * funcarg, VAR_t priority) inline
Task function. Creates a new task. The stack memory is fixed, its size is set by the architecture specific portion of the operating system.
Parameters
funcptr pointer to the function that shall be executed by the new task.
funcarg optional argument passed to function.
priority task priority. Must be in the range 0.. POSCFG_MAX_PRIO_LEVEL - 1. The higher the number, the higher the priority.
Returns
task creation status. -1 is returned when the task could not be created.
Note
POSCFG_TASKSTACKTYPE must be defined to 2 to have this format of the function compiled in.
See also
posTaskCreate, exit
References posTaskCreate().
static void pos::Task::init (POSTASKFUNC_t firstfunc, void * funcarg, VAR_t priority) inline static
Operating System Initialization. This function initializes the operating system and starts the first tasks: The idle task and the first user task.
Parameters
firstfunc pointer to the first task function that will run in the multitasking environment.
funcarg optional argument passed to the first task.
priority task priority. Must be in the range 0 .. POSCFG_MAX_PRIO_LEVEL - 1. The higher the number, the higher the priority.
Note
POSCFG_TASKSTACKTYPE must be defined to 2 to have this format of the function compiled in.
See also
posInit
References posInit().
static void pos::Task::exit (void) inline static
Terminate execution of a task.
Note
POSCFG_FEATURE_EXIT must be defined to 1 to have this function compiled in.
See also
posTaskExit, create
References posTaskExit().
static Task pos::Task::getCurrent (void) inline static
Get the currently running task.
Returns
the task.
Note
POSCFG_FEATURE_GETTASK must be defined to 1 to have this function compiled in.
See also
posTaskGetCurrent, create, setPriority
References posTaskGetCurrent().
VAR_t pos::Task::unused () inline
Tests if a task is yet in use by the operating system. This function can be used to test if a task has been fully terminated (and the stack memory is no more in use).
Returns
1 (=true) when the task is unused. If the task is still in use, zero is returned. A negative value is returned on error.
Note
POSCFG_FEATURE_TASKUNUSED must be defined to 1 to have this function compiled in.
See also
posTaskUnused, create, exit
References posTaskUnused().
VAR_t pos::Task::setPriority (VAR_t priority) inline
Change the priority of a task. Note that in a non-roundrobin scheduling environment every priority level can only exist once.
Parameters
priority new priority. Must be in the range 0 .. POSCFG_MAX_PRIO_LEVEL - 1. The higher the number, the higher the priority.
Returns
zero on success.
Note
POSCFG_FEATURE_SETPRIORITY must be defined to 1 to have this function compiled in.
See also
posTaskSetPriority, getPriority, getCurrent, create
References posTaskSetPriority().
VAR_t pos::Task::getPriority () inline
Get the priority of a task.
Returns
the priority of the task. A negative value is returned on error.
Note
POSCFG_FEATURE_GETPRIORITY must be defined to 1 to have this function compiled in.
See also
posTaskGetPriority, setPriority, getCurrent, create
References posTaskGetPriority().
static void pos::Task::schedLock (void) inline static
Locks the scheduler. When this function is called, no task switches will be done any more, until the counterpart function posTaskSchedUnlock is called. This function is usefull for short critical sections that require exclusive access to variables. Note that interrupts still remain enabled.
Note
POSCFG_FEATURE_INHIBITSCHED must be defined to 1 to have this function compiled in.
See also
posTaskSchedLock, schedUnlock
References posTaskSchedLock().
static void pos::Task::schedUnlock (void) inline static
Unlocks the scheduler. This function is called to leave a critical section. If a context switch request is pending, the context switch will happen directly after calling this function.
Note
POSCFG_FEATURE_INHIBITSCHED must be defined to 1 to have this function compiled in.
See also
posTaskSchedUnlock, schedLock
References posTaskSchedUnlock().
static void* pos::Task::getUserspace (void) inline static
Returns a pointer to the user memory in the current task control block.
Note
POSCFG_TASKCB_USERSPACE must be defined to a nonzero value to have this function compiled in. POSCFG_TASKCB_USERSPACE is also used to set the size of the user memory (in bytes).
Returns
pointer to user memory space.
See also
posTaskGetUserspace
References posTaskGetUserspace().
static POSIDLEFUNC_t pos::Task::installIdleTaskHook (POSIDLEFUNC_t idlefunc) inline static
Install or remove an optional idle task hook function. The hook function is called every time the system is idle. It is possible to use this hook to implement your own idle task; in this case the function does not need to return to the system. You may insert a call to posTaskYield into your idle task loop to get a better task performance.
Parameters
idlefunc function pointer to the new idle task handler. If this parameter is set to NULL, the idle task function hook is removed again.
Returns
This function may return a pointer to the last hook function set. If so (pointer is not NULL), the previous hook function should be called from within your idle task hook. This enables chaining of hook functions.
Note
POSCFG_FEATURE_IDLETASKHOOK must be defined to 1 to have this function compiled in.
See also
posInstallIdleTaskHook
References posInstallIdleTaskHook().
void pos::Task::setName (const char * name) inline
Assign a name to a pico]OS task.
This is useful when you are debugging your application by using the global tasklist that is referenced by the variable picodeb_tasklist. It is easier to navigate through the list when the tasks have names. Examples:
Task task;
task.create(workertaskfunc, NULL, 2);
task.setName("worker task");
Note
It is not necessary to use this macro when you are using the function nosTaskCreate to start a new task.
See also
POS_SETTASKNAME
References POS_SETTASKNAME.