picoos-oo: pos::Message Class Reference
pos::Message Class Reference
#include <picoos-msg.hxx>
Public Member Functions
Message ()
Message (void *buf)
void * alloc ()
void free ()
VAR_t send (const Task &task)
void * get ()
void * wait (UINT_t timeoutticks)
Static Public Member Functions
static VAR_t available ()
Detailed Description
Message boxes are a mechanism that is used for inter-process or, in the case of pico]OS, inter-task communication. All tasks can post messages to each other, and the receiving task will look into its message box and continues when it got a new message. Note that a message box in the pico]OS can hold chunk of messages, so that no message will be lost while the receiving task is still busy processing the last message.
There are two possible types of message boxes: The simple type can only hold a pointer to a user supplied buffer. The other message box type can hold whole messages with different sizes. A message buffer must be allocated with pos::Message::alloc by the sending task, and the receiving task must free this buffer again with pos::Message::free.
To select the simple message box type, you have to set the define POSCFG_MSG_MEMORY to 0. When you want to have the full message buffer support, you must set POSCFG_MSG_MEMORY to 1.
Constructor & Destructor Documentation
pos::Message::Message () inline
Construct message when POSCFG_MSG_MEMORY is 1.
pos::Message::Message (void * buf) inline
Construct message when POSCFG_MSG_MEMORY is 0.
Member Function Documentation
void* pos::Message::alloc () inline
Allocates a new message buffer. The maximum buffer size is set at compilation time by the define POSCFG_MSG_BUFSIZE. Usually the sending task would allocate a new message buffer, fill in its data and send it via posMessageSend to the receiving task.
Returns
the pointer to the new buffer. NULL is returned on error.
Note
POSCFG_FEATURE_MSGBOXES must be defined to 1 to have message box support compiled in.
POSCFG_MSG_MEMORY must be defined to 1 to have this function compiled in.
See also
posMessageAlloc, send, get, free
References posMessageAlloc().
static VAR_t pos::Message::available () inline static
Tests if a new message is available in the message box. This function can be used to prevent the task from blocking.
Returns
1 (=true) when a new message is available. Otherwise zero is returned. A negative value is returned on error.
Note
POSCFG_FEATURE_MSGBOXES must be defined to 1 to have message box support compiled in.
See also
posMessageAvailable, get, wait
References posMessageAvailable().
void pos::Message::free () inline
Frees a message buffer again. Usually the receiving task would call this function after it has processed a message to free the message buffer again.
Note
POSCFG_FEATURE_MSGBOXES must be defined to 1 to have message box support compiled in.
POSCFG_MSG_MEMORY must be defined to 1 to have this function compiled in.
See also
posMessageFree, get, send, alloc
References posMessageFree().
void* pos::Message::get () inline
Gets a new message from the message box. If no message is available, the task blocks until a new message is received.
Returns
pointer to the received message. Note that the message memory must be freed again with posMessageFree when POSCFG_MSG_MEMORY is defined to 1.
NULL may be returned when the system has not enough events. In this case, please increase the value for POSCFG_MAX_EVENTS in your poscfg.h .
Note
POSCFG_FEATURE_MSGBOXES must be defined to 1 to have message box support compiled in.
See also
posMessageGet, free, available, wait, send
References posMessageGet().
VAR_t pos::Message::send (const Task & task) inline
Sends a message to a task.
Parameters
task the task to send the message to.
Returns
zero on success. When an error condition exist, a negative value is returned and the message buffer is freed.
Note
POSCFG_FEATURE_MSGBOXES must be defined to 1 to have message box support compiled in.
See also
posMessageSend, alloc, get
References posMessageSend().
void* pos::Message::wait (UINT_t timeoutticks) inline
Gets a new message from the message box. If no message is available, the task blocks until a new message is received or the timeout has been reached.
Parameters
timeoutticks timeout in timer ticks (see HZ define and MS macro). If this parameter is set to zero, the function immediately returns. If this parameter is set to INFINITE, the function will never time out.
Returns
pointer to the received message. Note that the message memory must be freed again with posMessageFree when POSCFG_MSG_MEMORY is defined to 1. NULL is returned when no message was received within the specified time (=timeout).
Hint: NULL may also be returned when the system has not enough events. In this case, please increase the value for POSCFG_MAX_EVENTS in your poscfg.h .
Note
POSCFG_FEATURE_MSGBOXES must be defined to 1 to have message box support compiled in.
POSCFG_FEATURE_MSGWAIT must be defined to 1 to have this function compiled in.
See also
posMessageWait, free, get, available, send, HZ, MS
References posMessageWait().