picoos-oo: pos::Timer Class Reference
pos::Timer Class Reference
#include <picoos-timer.hxx>
Public Member Functions
VAR_t create ()
VAR_t set (const Sema &sema, UINT_t waitticks, UINT_t periodticks)
VAR_t start ()
VAR_t stop ()
void destroy ()
VAR_t fired ()
Detailed Description
A timer object is a counting variable that is counted down by the system timer interrupt tick rate. If the variable reaches zero, a semaphore, that is bound to the timer, will be signaled. If the timer is in auto reload mode, the timer is restarted and will signal the semaphore again and again, depending on the period rate the timer is set to.
Member Function Documentation
VAR_t pos::Timer::create () inline
Allocates a timer object. After a timer is allocated with this function, it must be set up with posTimerSet and than started with posTimerStart.
Returns
timer creation status. -1 is returned when the timer could not be created.
Note
POSCFG_FEATURE_TIMER must be defined to 1 to have timer support compiled in.
See also
posTimerCreate, set, start, destroy
References posTimerCreate().
VAR_t pos::Timer::set (const Sema & sema, UINT_t waitticks, UINT_t periodticks) inline
Sets up a timer object.
Parameters
sema seaphore object that shall be signaled when timer fires.
waitticks number of initial wait ticks. The timer fires the first time when this ticks has been expired.
periodticks After the timer has fired, it is reloaded with this value, and will fire again when this count of ticks has been expired (auto reload mode). If this value is set to zero, the timer won't be restarted (= one shot mode).
Returns
zero on success.
Note
POSCFG_FEATURE_TIMER must be defined to 1 to have timer support compiled in.
See also
posTimerSet, create, start
References posTimerSet().
VAR_t pos::Timer::start () inline
Starts a timer. The timer will fire first time when the waitticks counter has been reached zero. If the periodticks were set, the timer will be reloaded with this value.
Returns
zero on success.
Note
POSCFG_FEATURE_TIMER must be defined to 1 to have timer support compiled in.
See also
posTimerStart, stop, fired
References posTimerStart().
VAR_t pos::Timer::stop () inline
Stops a timer. The timer will no more fire. The timer can be reenabled with posTimerStart.
Returns
zero on success.
Note
POSCFG_FEATURE_TIMER must be defined to 1 to have timer support compiled in.
See also
posTimerStop, start, destroy
References posTimerStop().
void pos::Timer::destroy () inline
Deletes a timer object and free its resources.
Note
POSCFG_FEATURE_TIMER must be defined to 1 to have timer support compiled in.
POSCFG_FEATURE_TIMERDESTROY must be defined to 1 to have this function compiled in.
See also
posTimerDestroy, create
References posTimerDestroy().
VAR_t pos::Timer::fired () inline
The function is used to test if a timer has fired.
Returns
1 when the timer has fired, otherwise 0. A negative value is returned on error.
Note
POSCFG_FEATURE_TIMER must be defined to 1 to have timer support compiled in.
POSCFG_FEATURE_TIMERFIRED must be defined to 1 to have this function compiled in.
See also
posTimerFired, create, set, start
References posTimerFired().