picoos-oo: nos::Message Class Reference
nos::Message Class Reference
#include <picoos-msg.hxx>
Public Member Functions
void * alloc (UINT_t msgSize)
void free ()
VAR_t send (const Task &task)
Public Member Functions inherited from pos::Message
Message ()
Message (void *buf)
void * alloc ()
void free ()
VAR_t send (const Task &task)
void * get ()
void * wait (UINT_t timeoutticks)
Additional Inherited Members
Static Public Member Functions inherited from pos::Message
static VAR_t available ()
Detailed Description
Messagephore functions.
Member Function Documentation
void* nos::Message::alloc (UINT_t msgSize) inline
Allocates a new message buffer. To increase the execution speed, it is recommended to set POSCFG_MSG_MEMORY to 1. Otherwise, nosMessageAlloc will need to call nosMemAlloc to allocate memory (and this is possibly slower than the pico]OS internal message allocator).
Usually the sending task would allocate a new message buffer, fill in its data and send it via nosMessageSend to the receiving task. The receiving task is responsible for freeing the message buffer again.
Parameters
msgSize size of the requested message buffer in bytes.
Returns
the pointer to the new buffer. NULL is returned if the system is low on memory or the requested msgSize is larger than POSCFG_MSG_BUFSIZE (only if POSCFG_MSG_MEMORY is set to 1).
Note
NOSCFG_FEATURE_MSGBOXES must be defined to 1 to have message box support compiled in.
If POSCFG_MSG_MEMORY is set to 0, you also need to enable the nano layer memory manager by setting NOSCFG_FEATURE_MEMALLOC to 1.
See also
nosMessageSend, nosMessageGet, nosMessageFree
References nosMessageAlloc().
void nos::Message::free () inline
Frees a message buffer again. Usually the receiving task would call this function after it has processed a message to free the message buffer again.
Note
NOSCFG_FEATURE_MSGBOXES must be defined to 1 to have message box support compiled in.
See also
nosMessageGet, nosMessageSend, nosMessageAlloc
References nosMessageFree().
VAR_t nos::Message::send (const Task & task) inline
Sends a message to a task.
Parameters
task handle to the task to send the message to.
Returns
zero on success. When an error condition exist, a negative value is returned and the message buffer is freed.
Note
NOSCFG_FEATURE_MSGBOXES must be defined to 1 to have message box support compiled in.
See also
nosMessageAlloc, nosMessageGet
References nosMessageSend().