picoos-oo: pos::SoftInt Class Reference
pos::SoftInt Class Reference
#include <picoos-softint.hxx>
Static Public Member Functions
static void raise (UVAR_t intno, UVAR_t param)
static VAR_t setHandler (UVAR_t intno, POSINTFUNC_t inthandler)
static VAR_t delHandler (UVAR_t intno)
Detailed Description
pico]OS has a built in mechanism to simulate software interrupts. For example, software interrupts can be used to connect hardware interrupts, that are outside the scope of pico]OS, to the realtime operating system. A hardware interrupt will trigger a software interrupt that can then signalize a semaphore object.
Note that hardware interrupts, that do not call c_pos_intEnter and c_pos_intExit, can't do calls to pico]OS functions, except to the function pos::SoftInt::raise.
All software interrupts, that are triggered by a call to pos::SoftInt::raise, are chained into a global list. This list is then executed as soon as possible, but at least when the pico]OS scheduler is called (that is, for example, when a time slice has expired or a task gives of processing time by itself).
A software interrupt runs at interrupt level, that means with interrupts disabled (pico]OS calls POS_SCHED_LOCK before executing the software interrupt handler). The execution of software interrupt handlers can not be inhibited by setting the pos::Task::schedLock flag.
Note that software interrupts need additional space on the processors call stack. Make sure to have space for at least 5 additional subroutine calls, plus the calls you will make in the ISR handler routine.
Member Function Documentation
static void pos::SoftInt::raise (UVAR_t intno, UVAR_t param) inline static
Rises a software interrupt. The software interrupt handler will be executed as soon as possible. See above for a detailed description.
Parameters
intno number of the interrupt to rise. Must be in the range of 0 to POSCFG_SOFTINTERRUPTS - 1.
param optional parameter that will be passed to the software interrupt handler funtion.
Note
POSCFG_FEATURE_SOFTINTS must be defined to 1 to have software interrupt support compiled in.
If a software interrupt is triggered from inside the pico]OS scope, usually from application level, it is recommended to do a call to posTaskYield after this function is called. This will immediately start the interrupt handler.
See also
posSoftInt, setHandler, delHandler, POSCFG_SOFTINTQUEUELEN
References posSoftInt().
static VAR_t pos::SoftInt::setHandler (UVAR_t intno, POSINTFUNC_t inthandler) inline static
Sets a software interrupt handler function. Before a software interrupt can be rised by a call to posSoftInt, this function must be called to tell pico]OS the handler function for the interrupt.
Parameters
intno number of the interrupt to rise. Must be in the range of 0 to POSCFG_SOFTINTERRUPTS - 1.
inthandler pointer to the interrupt handler function.
Note
POSCFG_FEATURE_SOFTINTS must be defined to 1 to have software interrupt support compiled in.
Returns
zero on success.
See also
posSoftIntSetHandler, delHandler, raise
References posSoftIntSetHandler().
static VAR_t pos::SoftInt::delHandler (UVAR_t intno) inline static
Deletes a software interrupt handler function, that was set with posSoftIntSetHandler before.
Parameters
intno number of the interrupt to rise. Must be in the range of 0 to POSCFG_SOFTINTERRUPTS - 1.
Note
POSCFG_FEATURE_SOFTINTS must be defined to 1 to have software interrupt support compiled in.
POSCFG_FEATURE_SOFTINTDEL must be defined to 1 to have this function compiled in.
Returns
zero on success.
See also
posSoftIntDelHandler, setHandler, raise
References posSoftIntDelHandler().