picoos-oo: pos::Atomic Class Reference
pos::Atomic Class Reference
#include <picoos-atomic.hxx>
Public Member Functions
void set (INT_t value)
INT_t get ()
INT_t add (INT_t value)
INT_t sub (INT_t value)
Detailed Description
Atomic variables are variables that can be accessed in an atomic manner, that means a read-modify-write instruction is done in virtually one single cycle. For example, the atomic access to a variable is necessary when two tasks will do read-modify-write operations on a common variable. Under usual circumstances you can ran into trouble when a task that is just modifying the variable (that means it has read and modified the variable but has not yet written the result back) is interrupted by a second task that also modifies the variable. Thus the modification the first task has done would be lost. Atomic variables prevent this possible race condition.
Member Function Documentation
void pos::Atomic::set (INT_t value) inline
Sets an atomic variable to the specified value.
Parameters
value the value the atomic variable shall be set to.
Note
POSCFG_FEATURE_ATOMICVAR must be defined to 1 to have atomic variable support compiled in.
See also
posAtomicSet, get, add, sub
References posAtomicSet().
INT_t pos::Atomic::get () inline
Returns the current value of an atomic variable.
Returns
the value of the atomic variable.
Note
POSCFG_FEATURE_ATOMICVAR must be defined to 1 to have atomic variable support compiled in.
See also
posAtomicGet, set, add, sub
References posAtomicGet().
INT_t pos::Atomic::add (INT_t value) inline
Adds a value onto the current value of the atomic variable.
Parameters
value value that shall be added to the atomic variable.
Returns
the content of the atomic variable before it was incremented.
Note
POSCFG_FEATURE_ATOMICVAR must be defined to 1 to have atomic variable support compiled in.
See also
posAtomicAdd, set, get, sub
References posAtomicAdd().
INT_t pos::Atomic::sub (INT_t value) inline
Substracts a value from the current value of the atomic variable.
Parameters
value value that shall be substracted from the atomic variable.
Returns
the content of the atomic variable before it was decremented.
Note
POSCFG_FEATURE_ATOMICVAR must be defined to 1 to have atomic variable support compiled in.
See also
posAtomicSub, set, get, add
References posAtomicSub().