picoos-oo: nos::Console Class Reference
nos::Console Class Reference
#include <picoos-console.hxx>
Static Public Member Functions
static char keyGet ()
static UVAR_t keyPressed ()
static void printChar (char c)
static void print (const char *s)
static void printf (const char *fmt,...)
Detailed Description
Console input and output. Typically uses serial port.
Member Function Documentation
static char nos::Console::keyGet () inline static
Wait and get the code of the next pressed key. This function blocks until the user presses a key on the keyboard and returns the code of the pressed key as result.
Returns
ASCII-code of the pressed key
Note
NOSCFG_FEATURE_CONIN must be defined to 1 to have this function compiled in.
See also
nosKeyGet, keyPressed, c_nos_keyinput, NOSCFG_CONIO_KEYBUFSIZE
References nosKeyGet().
static UVAR_t nos::Console::keyPressed () inline static
Test if a key was pressed. This function tests if a key code is available in the keyboard buffer. Even if no key is pressed yet, the function will immediately return.
Returns
TRUE (nonzero) when a key code is available.
Note
NOSCFG_FEATURE_CONIN must be defined to 1 to have this function compiled in.
See also
nosKeyPressed, keyGet, c_nos_keyinput, NOSCFG_CONIO_KEYBUFSIZE
References nosKeyPressed().
static void nos::Console::printChar (char c) inline static
Print a character to the console or terminal. This function prints a single character to the console. No CR/LF conversion is performed.
Note
NOSCFG_FEATURE_CONOUT must be defined to 1 to have this function compiled in.
See also
nosPrintChar, print, p_putchar
References nosPrintChar().
static void nos::Console::print (const char * s) inline static
Print a character string to the console or terminal. This function prints a string of characters (text) to the console. A CR/LF conversion is performed, CR is preceding each LF.
Parameters
s pointer to zero terminated ASCII string
Note
NOSCFG_FEATURE_CONOUT must be defined to 1 to have this function compiled in.
See also
nosPrint, printChar, p_putchar
References nosPrint().
static void nos::Console::printf (const char * fmt, ...) static
Print a formated character string to the console or terminal. This function acts like the usual printf function, except that it is limmited to the basic formats. The largest integer that can be displayed is of type INT_t.
Parameters
fmt format string
Note
NOSCFG_FEATURE_CONOUT and NOSCFG_FEATURE_PRINTF must be defined to 1 to have this function compiled in.
This function is supported only if ::NOSCFG_FEATURE_USE_STDARG is defined to 1.
See also
printChar, print