picoos-oo: pos::Flag Class Reference
pos::Flag Class Reference
#include <picoos-flag.hxx>
Public Member Functions
VAR_t create ()
void destroy ()
VAR_t set (UVAR_t flgnum)
VAR_t get (UVAR_t mode)
VAR_t wait (UINT_t timeoutticks)
Detailed Description
Flags are one-bit semaphores. They can be used to simulate events. A thread can simultaneousely wait for multiple flags to be set, so it is possible to post multiple events to this thread. The count of events a flag object can handle is only limited by the underlaying architecutre, the maximum count is defined as MVAR_BITS - 1.
Member Function Documentation
VAR_t pos::Flag::create () inline
Allocates a flag object. A flag object behaves like an array of one bit semaphores. The object can hold up to MVAR_BITS - 1 flags. The flags can be used to simulate events, so a single thread can wait for several events simultaneously.
Returns
flag creation status. -1 is returned when the flag could not be created.
Note
POSCFG_FEATURE_FLAGS must be defined to 1 to have flag support compiled in.
See also
posFlagCreate, get, set, destroy
References posFlagCreate().
void pos::Flag::destroy () inline
Frees an unused flag object again.
Note
POSCFG_FEATURE_FLAGS must be defined to 1 to have flag support compiled in.
POSCFG_FEATURE_FLAGDESTROY must be defined to 1 to have this function compiled in.
See also
posFlagDestroy, create
References posFlagDestroy().
VAR_t pos::Flag::set (UVAR_t flgnum) inline
Sets a flag bit in the flag object and sets the Flag that pends on the flag object to running state.
Parameters
flgnum Number of the flag to set. The flag number must be in the range of 0 .. MVAR_BITS - 2.
Returns
zero on success.
Note
POSCFG_FEATURE_FLAGS must be defined to 1 to have flag support compiled in.
See also
posFlagSet, create, get, wait
References posFlagSet().
VAR_t pos::Flag::get (UVAR_t mode) inline
Pends on a flag object and waits until one of the flags in the flag object is set.
Parameters
mode can be POSFLAG_MODE_GETSINGLE or POSFLAG_MODE_GETMASK.
Returns
the number of the next flag that is set when mode is set to POSFLAG_MODE_GETSINGLE. When mode is set to POSFLAG_MODE_GETMASK, a bit mask with all set flags is returned. A negative value is returned on error.
Note
POSCFG_FEATURE_FLAGS must be defined to 1 to have flag support compiled in.
See also
posFlagGet, create, set, wait
References posFlagGet().
VAR_t pos::Flag::wait (UINT_t timeoutticks) inline
Pends on a flag object and waits until one of the flags in the flag object is set or a timeout has happened.
Parameters
timeoutticks timeout in timer ticks (see HZ define and MS macro). If this parameter is set to zero, the function immediately returns. If this parameter is set to INFINITE, the function will never time out.
Returns
a mask of all set flags (positive value). If zero is returned, the timeout was reached. A negative value denotes an error.
Note
POSCFG_FEATURE_FLAGS must be defined to 1 to have flag support compiled in.
POSCFG_FEATURE_FLAGWAIT must be defined to 1 to have this function compiled in.
See also
posFlagWait, create, set, get, HZ, MS
References posFlagWait().