picoos-oo: pos::Mutex Class Reference
pos::Mutex Class Reference
#include <picoos-mutex.hxx>
Public Member Functions
VAR_t create ()
void destroy ()
VAR_t tryLock ()
VAR_t lock ()
VAR_t unlock ()
Detailed Description
Mutexes are used for task synchronization. A source code area that is protected by a mutex can only be executed by one task at the time. The mechanism is comparable with a semaphore that is initialized with a counter of 1. A mutex is a special semaphore, that allows a task having the mutex locked can execute the mutex lock functions again and again without being blocked (this is called reentrancy).
Member Function Documentation
create()
VAR_t pos::Mutex::create () inline
Allocates a new mutex object.
Returns
mutex creation status. -1 is returned when the mutex could not be created.
Note
POSCFG_FEATURE_MUTEXES must be defined to 1 to have mutex support compiled in.
See also
posMutexCreate, destroy, lock, tryLock, unlock
References posMutexCreate().
Referenced by nos::Mutex::create().
destroy()
void pos::Mutex::destroy () inline
Frees a no more needed mutex object.
Note
POSCFG_FEATURE_MUTEXES must be defined to 1 to have mutex support compiled in.
POSCFG_FEATURE_MUTEXDESTROY must be defined to 1 to have this function compiled in.
See also
posMutexDestroy, create
References posMutexDestroy().
tryLock()
VAR_t pos::Mutex::tryLock () inline
Tries to get the mutex lock. This function does not block when the mutex is not available, instead it returns a value showing that the mutex could not be locked.
Returns
zero when the mutex lock could be set. Otherwise, when the mutex lock is yet helt by an other task, the function returns 1. A negative value is returned on error.
Note
POSCFG_FEATURE_MUTEXES must be defined to 1 to have mutex support compiled in.
POSCFG_FEATURE_MUTEXTRYLOCK must be defined to 1 to have this function compiled in.
See also
posMutexTryLock, lock, unlock, create
References posMutexTryLock().
lock()
VAR_t pos::Mutex::lock () inline
This function locks a code section so that only one task can execute the code at a time. If an other task already has the lock, the task requesting the lock will be blocked until the mutex is unlocked again. Note that a posMutexLock appears always in a pair with posMutexUnlock.
Returns
zero on success.
Note
POSCFG_FEATURE_MUTEXES must be defined to 1 to have mutex support compiled in.
See also
posMutexLock, tryLock, unlock, create
References posMutexLock().
unlock()
VAR_t pos::Mutex::unlock () inline
This function unlocks a section of code so that other tasks are able to execute it.
Returns
zero on success.
Note
POSCFG_FEATURE_MUTEXES must be defined to 1 to have mutex support compiled in.
See also
posMutexUnlock, lock, tryLock, create
References posMutexUnlock().